### ISSUE TITLE
I made a simplified Chinese json, and I hope it can be used in subsequent versions.

### ISSUE THREAD

**Issue by shenyx110** [pufmat/skillsmod#10]
我做了一个简体中文json 希望可以用于后续版本

I made a simplified Chinese json, and I hope it can be used in subsequent versions.

{
	"text.puffish_skills.skills": "技能",
	"text.puffish_skills.points_left": "剩余点: ",

	"category.puffish_skills.skills": "技能",
	"key.puffish_skills.open": "打开技能树",

	"chat.puffish_skills.new_point": "你有一个新的技能点。按%s打开你的技能树."
}

**Comment by pufmat** [comment]
Added in 0.5.0
