### ISSUE TITLE
Cannot join my server on a Different PC with the same account, but singleplayer works fine.

### ISSUE THREAD

**Issue by VortexOle** [pufmat/skillsmod#101]
I I recently had to reinstall my Windows and so I lost alot of my files, including Minecraft related. After I tried joining the server my friends and I play on with baisicly the same mods, I instantly get kicked with this error: "icom.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $" but why I tried creating a singleplayer world, it opened just fine. From how it sounds it's prolly a server side issue but im not sure how to fix it...
this is the latest log relating to the error. 
[latest.log](https://github.com/user-attachments/files/16425073/latest.log)

Thank you in advance!

**Comment by VortexOle** [comment]
I tried to manually edit the puffish_skills.dat file with NBTExplorer on the server to remove the old stuff and restarted it but I still get the same error. I forgot to mention that the server and the client runs Fabric 1.20.2

**Comment by pufmat** [comment]
This is very unlikely to be related to the `puffish_skills.dat`. Please make sure you use the same version of the mod on the server and client.

**Comment by VortexOle** [comment]
Hey there, really sorry for the late reply, I completely forgot about this. Turns out I still had the I believe v0.9.0 on the server while I tried to join with v0.13.0.
