### ISSUE TITLE
You keep gaining skill points even after maxing out the skill tree

### ISSUE THREAD

**Issue by Saereth** [pufmat/skillsmod#102]
Would it be possible to get a config to hard limit the amount of skill points a player can earn? Maybe something like this already exists but I couldnt find it in the wikii/datapacks. Thanks!

**Comment by pufmat** [comment]
It is already possible to configure the limit. Set `spent_points_limit` to a value you want in `category.json` file. More information in the [documentation of that file](https://puffish.net/skillsmod/docs/creators/configuration/files/category#spent-points-limit).

**Comment by Saereth** [comment]
perfect, ty!
