### ISSUE TITLE
Expected a valid operation

### ISSUE THREAD

**Issue by iStryka** [pufmat/skillsmod#109]
Minecraft version 1.19.2
puffish attributes 0.6.0
puffish skills 0.14.1
Modpack used Dimensional Ascension 0.7.1b

Running into an error for operations and dropped xp and max_health variable unknown.

Expected a valid operation type at `type` at index 0 at `operations` at `max_health` at `variables` at `data` at index 0 at `sources` at `categories\combat\experience.json`
Expected a valid operation type at `type` at index 0 at `operations` at `dropped_xp` at `variables` at `data` at index 0 at `sources` at `categories\combat\experience.json`
Unknown variable `dropped_xp` at `expression` at index 0 at `experience` at `data` at index 0 at `sources` at `categories\combat\experience.json`
Unknown variable `max_health` at `expression` at index 0 at `experience` at `data` at index 0 at `sources` at `categories\combat\experience.json`

Initially I was getting a rewards error calling 'rewards' at 'skill names' but that was fixed after adding puffish attributes, then now stuck with operations within the experience.json file

**Comment by Kamkarot** [comment]
I am having the same issue. I installed from CurseForge, 
Pufferfish's Skills [Fabric & Forge & NeoForge] 
Pufferfish's Attributes [Fabric & Forge & NeoForge]
Default Skill Trees
`[Server thread/ERROR]: [puffish_skills] Mod configuration could not be loaded:
Expected a valid operation type at `type` at index 0 at `operations` at `max_health` at `variables` at `data` at index 0 at `sources` at `categories\combat\experience.json`
Expected a valid operation type at `type` at index 0 at `operations` at `dropped_xp` at `variables` at `data` at index 0 at `sources` at `categories\combat\experience.json`
Unknown variable `dropped_xp` at `expression` at index 0 at `experience` at `data` at index 0 at `sources` at `categories\combat\experience.json`
Unknown variable `max_health` at `expression` at index 0 at `experience` at `data` at index 0 at `sources` at `categories\combat\experience.json`
Expected a valid operation type at `type` at index 0 at `operations` at `deepslate` at `variables` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Expected a valid operation type at `type` at index 0 at `operations` at `copper_ore` at `variables` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Expected a valid operation type at `type` at index 0 at `operations` at `gold_ore` at `variables` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Expected a valid operation type at `type` at index 0 at `operations` at `redstone_ore` at `variables` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Expected a valid operation type at `type` at index 0 at `operations` at `stone_like` at `variables` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Expected a valid operation type at `type` at index 0 at `operations` at `deepslate_redstone_ore` at `variables` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Expected a valid operation type at `type` at index 0 at `operations` at `silk_touch` at `variables` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Expected a valid operation type at `type` at index 0 at `operations` at `deepslate_emerald_ore` at `variables` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Expected a valid operation type at `type` at index 0 at `operations` at `iron_ore` at `variables` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Expected a valid operation type at `type` at index 0 at `operations` at `diamond_ore` at `variables` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Expected a valid operation type at `type` at index 0 at `operations` at `deepslate_copper_ore` at `variables` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Expected a valid operation type at `type` at index 0 at `operations` at `lapis_ore` at `variables` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Expected a valid operation type at `type` at index 0 at `operations` at `coal_ore` at `variables` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Expected a valid operation type at `type` at index 0 at `operations` at `deepslate_iron_ore` at `variables` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Expected a valid operation type at `type` at index 0 at `operations` at `deepslate_lapis_ore` at `variables` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Expected a valid operation type at `type` at index 0 at `operations` at `emerald_ore` at `variables` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Expected a valid operation type at `type` at index 0 at `operations` at `deepslate_coal_ore` at `variables` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Expected a valid operation type at `type` at index 0 at `operations` at `deepslate_gold_ore` at `variables` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Expected a valid operation type at `type` at index 0 at `operations` at `deepslate_diamond_ore` at `variables` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Unknown variable `silk_touch` at `condition` at index 0 at `experience` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Unknown variable `stone_like` at `condition` at index 0 at `experience` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Unknown variable `silk_touch` at `condition` at index 1 at `experience` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Unknown variable `deepslate` at `condition` at index 1 at `experience` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Unknown variable `silk_touch` at `condition` at index 2 at `experience` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Unknown variable `coal_ore` at `condition` at index 2 at `experience` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Unknown variable `copper_ore` at `condition` at index 2 at `experience` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Unknown variable `iron_ore` at `condition` at index 2 at `experience` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Unknown variable `gold_ore` at `condition` at index 2 at `experience` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Unknown variable `redstone_ore` at `condition` at index 2 at `experience` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Unknown variable `lapis_ore` at `condition` at index 2 at `experience` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Unknown variable `diamond_ore` at `condition` at index 2 at `experience` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Unknown variable `emerald_ore` at `condition` at index 2 at `experience` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Unknown variable `silk_touch` at `condition` at index 3 at `experience` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Unknown variable `deepslate_coal_ore` at `condition` at index 3 at `experience` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Unknown variable `deepslate_copper_ore` at `condition` at index 3 at `experience` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Unknown variable `deepslate_iron_ore` at `condition` at index 3 at `experience` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Unknown variable `deepslate_gold_ore` at `condition` at index 3 at `experience` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Unknown variable `deepslate_redstone_ore` at `condition` at index 3 at `experience` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Unknown variable `deepslate_lapis_ore` at `condition` at index 3 at `experience` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Unknown variable `deepslate_diamond_ore` at `condition` at index 3 at `experience` at `data` at index 0 at `sources` at `categories\mining\experience.json`
Unknown variable `deepslate_emerald_ore` at `condition` at index 3 at `experience` at `data` at index 0 at `sources` at `categories\mining\experience.json``

**Comment by Kamkarot** [comment]
I don't know if it is a fix for iStryka, but uninstalling all and actually deleting the puffish folders etc. Then installing Pufferfish's Attributes, launching and ensuring the attributes are available (/attributes @s puff ) this should show if they are installed correctly. Then installing the other parts, pufferfish skills , default skill tree, has worked.

**Comment by iStryka** [comment]
@Kamkarot I will try that when I am not busy.

**Comment by pufmat** [comment]
@Kamkarot Default Skill Trees data pack is intended to be put into data packs folder, but you have put it into the mod configuration folder. It is possible to do that this way, but you need to decrease `version` in `config.json` to `2`, because when it is set to `3` legacy features that this data pack uses are not allowed. Alternatively you can download updated 1.1 version of Default Skill Trees data pack, that I have just uploaded, which it is compatible with configuration version `3`.

**Comment by pufmat** [comment]
@iStryka In your case I can't tell from the logs how you have installed Default Skill Trees, but solutions are the same. Decrease configuration version or update the Default Skill Trees. There is also [Default Skill Trees mod](https://www.curseforge.com/minecraft/mc-mods/default-skill-trees) which is a bit easier to install.

**Comment by pufmat** [comment]
I assume you both got these errors after doing either of these:
- Copying categories from data pack into mod configuration folder, and using `config.json` generated by to mod which had `version` set to `3`.
- Manually increasing version in `config.json` because the warning in the logs said to do so.

If none of these describe your case please let me know, because otherwise there may be a bug in the mod.

**Comment by iStryka** [comment]
> I assume you both got these errors after doing either of these:
> 
> * Copying categories from data pack into mod configuration folder, and using `config.json` generated by to mod which had `version` set to `3`.
> * Manually increasing version in `config.json` because the warning in the logs said to do so.
> 
> If none of these describe your case please let me know, because otherwise there may be a bug in the mod.

My issue is fixed after completely removing the modpack, reinstalling a clean slate of it with the latest pufferfish and installing everything manually afterwards via data pack zip, what borked it was the older pufferfish mod that didn't need to use the datapack so my assumption is the datapack + conflicting old folders. So from that, I re-imported all of my custom attributes I had into the data pack zip and everything is working well.
