### ISSUE TITLE
Chat notifications

### ISSUE THREAD

**Issue by Jer6776** [pufmat/skillsmod#11]
is there any way to disable the chat notifications so it doesn't pop up so frequently? I tried looking in the config but couldn't find anything, forge 44.1.23, version 1.19.3

**Comment by pufmat** [comment]
Would a game rule like `announceAdvancements` be an acceptable solution?

**Comment by Jer6776** [comment]
that’d be awesome!!

**Comment by pufmat** [comment]
Added in 0.4.0

**Comment by thimblebird** [comment]
the gamerule does nothing and the gamerule `announceNewPoints` (spotted in common server code) doesn't exist (minecraft 1.20.1, mod version 0.14.1 fabric)

//e:
mere seconds after commenting i found the gamerule. for anyone wondering:
`/gamerule puffish_skills:announceNewPoints false`
