### ISSUE TITLE
Visually broken skill tree

### ISSUE THREAD

**Issue by lingeringone** [pufmat/skillsmod#112]
![image](https://github.com/user-attachments/assets/a669870b-c402-412f-93e6-cbf15643dcc9)
Using the 1.21.3 default skill tree mod or datapack most of the textures don't render, but the buttons appear to still be there and function properly. Refreshing or clearing the textures don't do anything. I have both the puffish skills and attributes installed and I'm using the fabric version of the mod.

**Comment by pufmat** [comment]
Thanks for reporting. This issue is already fixed in mod version 0.14.4.
