### ISSUE TITLE
Problem with latest version -> puffish_skills-0.3.0-1.19.3-fabric.jar

### ISSUE THREAD

**Issue by Cape-City** [pufmat/skillsmod#12]
Hi,

I'm using MC 1.19.3 on fabric and when loading into the game, this message appears:

![grafik](https://github.com/pufmat/skillsmod/assets/122229367/976f9f1f-29b0-4d8f-b773-8da5e3524f1d)

The file is created, but complete empty:

![grafik](https://github.com/pufmat/skillsmod/assets/122229367/992185d4-20ef-48c8-abe5-a682d100f441)

This is also shown in the log:

![grafik](https://github.com/pufmat/skillsmod/assets/122229367/e4a60711-e3e7-4ac8-819a-6a02017d6c37)

[latest.log](https://github.com/pufmat/skillsmod/files/11490518/latest.log)

Hope i don't forgot something to report.

**Comment by pufmat** [comment]
Thanks for reporting. 

You have an outdated configuration, because you probably updated the mod. You can migrate the configuration (check wiki for more information) or remove it entirely to restore default. 

However, this is still and issue because the error message is misleading, it should say the configuration is outdated. It will be fixed in the next release.

**Comment by Cape-City** [comment]
You're right - i thought i used a fresh profile and installed the latest mod the first time. I forgot that i tested weeks before some things within this profile and had your mod installed :/ When i delete the config everything is as it should be.

I'm a creator of a modpack on CurseForge and if people just update their profile due CurseForge, it could be a bit tricky for them to migrate something or browse into their filesystem to delete the config folder. I can bring the config for the mod within my next release, but then i overwrite existing files.

What information you're storing within these files? Do you store the reached levels and selected skills also there?

I can do the german translation for the new message, if you know what you wanna say, before you release the next version (if you want?)

**Comment by pufmat** [comment]
You can override config without any problem.

Player data is stored in a world folder, in file `WORLD_NAME/data/puffish_skills.dat`.

The message about outdated config is already implemented, but it is not shown when the file is empty. There is no translation for it, as it is only visible in game logs.

**Comment by Cape-City** [comment]
Everything now works as it should ;) thanx for your help!
