### ISSUE TITLE
Cost doesn't work as intended

### ISSUE THREAD

**Issue by DeKogen** [pufmat/skillsmod#15]
Cost doesn't set the amount of points you'll need to spent on skill but a threshold under which u cant learn it (still cost 1 point).
Example: cost set to 2, if u have 1 point than u can't learn it, if u have 2 points than u can learn it and will left with 1 point (instead of 0).
Here is definition that I used.

	"luck+0.25": {
		"cost": 2,
		"title": "+0.25 Luck",
		"icon": {
			"type": "effect",
			"data": {
				"effect": "luck"
			}
		},
		"rewards": [
			{
				"type": "puffish_skills:attribute",
				"data": {
					"attribute": "generic.luck",
					"value": 0.25,
					"operation": "addition"
				}
			}
		]
	}

**Comment by pufmat** [comment]
Thanks for reporting.

**Comment by pufmat** [comment]
Fixed in 0.4.0
