### ISSUE TITLE
Mining skill allows to mine non pickaxe blocks faster than normal

### ISSUE THREAD

**Issue by SquareBall789** [pufmat/skillsmod#16]
Having a decent amount of mining skills paired with an efficiency pickaxe allow the player to break non pickaxe blocks a lot faster.

For instance:
maxxed out mining skill tree + efficiency IV diamond pickaxe allow almost insta mining of oak planks.

The same isnt true in reverse

maxxed out mining skill tree + efficiency IV diamond axe = mining stone at regular slow speed.

Using version: 0.3.0-1.19.2

**Comment by pufmat** [comment]
Fixed in 0.4.0

**Comment by SquareBall789** [comment]
Thank you!
