### ISSUE TITLE
Data structure question

### ISSUE THREAD

**Issue by Sweenus** [pufmat/skillsmod#19]
Hey there,

I'm currently working on a mod that includes Puffish Skills as a dependency in order to grant the player some more complex passive abilities. I'm running into trouble understanding how to pack the datafiles into my mod.

In my testing, I've been keeping my definitions, skills, etc in the run>config of my dev environment. This has been working well, however, I would like to have these files included in the mod itself when it's shipped.

I've tried adding the datafiles to my resources>data, using the folder structure outlined here:  https://github.com/pufmat/skillsmod/wiki/Configuration-Structure

This doesn't work, and the files are completely ignored. Is there something I'm missing, or is there currently no way to use these datafiles outside of Puffish Skill's config folder?

**Comment by pufmat** [comment]
There is no other way than Pufferfish's Skills config directory. You can try adding files to this directory using your mod.

**Comment by Sweenus** [comment]
Thanks for getting back to me - that clears things up.
Are you considering expanding upon this system to allow for easier modImplementation?

**Comment by pufmat** [comment]
Since version 0.6.0 you can ship your configuration as a data pack. Read more [here](https://github.com/pufmat/skillsmod/wiki/Configuration-Data-Packs).

**Comment by Sweenus** [comment]
This works great!
Thank you for implementing this feature - this will be fantastic for user-experience 🙂

**Comment by Sweenus** [comment]
@pufmat 
I think there may be an issue with the interpretation of formatting codes when the trees are loaded via datapacks.
In the images attached you can see two identical trees, one loaded via the config folder, and one via the data folder of a mod.
The one loaded via the data folder has some of the format code appearing when it shouldn't.

Interestingly, this issue does not occur in my dev environment (IntelliJ), only when deployed in a live-environment.
![Screenshot 2023-08-02 145503](https://github.com/pufmat/skillsmod/assets/48658188/ab46d0bb-05fb-412d-9ef8-36facc31b529)
![Screenshot 2023-08-02 145510](https://github.com/pufmat/skillsmod/assets/48658188/7cd9916f-1690-4d5e-8dac-07f24ad9e40a)

**Comment by pufmat** [comment]
Make sure your configuration files are encoded in UTF-8.

**Comment by Sweenus** [comment]
> Make sure your configuration files are encoded in UTF-8.

They are all UTF-8.
You can see the formatting being read and deployed as the text is colored. But it's transforming and displaying what is supposed to be '§' and is supposed to be hidden.
![Screenshot 2023-08-02 195854](https://github.com/pufmat/skillsmod/assets/48658188/c1beceee-8d03-462d-b7ab-6e99244cd377)

**Comment by Sweenus** [comment]
@pufmat Do you want me to open a separate ticket for this issue?

**Comment by pufmat** [comment]
No, need. I was able to reproduce this issue on Windows, I'll release a fix today.

**Comment by Sweenus** [comment]
> No, need. I was able to reproduce this issue on Windows, I'll release a fix today.

Oh, that's fantastic! Thank you so much for the speedy fix 🙂
