### ISSUE TITLE
[Suggestion] Add a Builder skill tree

### ISSUE THREAD

**Issue by ghost** [pufmat/skillsmod#2]
Expirience for skill tree can be gained by unique placing of decorative blocks (class of decorative blocks needs to be custom)
Skills in the tree:
1) Decrease placing blocks cooldown by 5%
2) Increase reach for block placement by 0.1 blocks
3) Increase jump height by 5%
4) Final level ffor each end of tree: adding and increasing chance to not spend block when placed (works only 1 time for each block and if  block spended it cannot be rerolled again for duping)

**Comment by Sazuzaki** [comment]
Pretty sure you can do this yourself through the use of datapacks. Take a look at the wiki
