### ISSUE TITLE
Exclusive root option does not seem to be working

### ISSUE THREAD

**Issue by Sweenus** [pufmat/skillsmod#23]
On the latest version, and also the previous version, the exclusive roots option in the category.json does not seem to work.
You are able to loop around to a locked root and unlock it. I assume this is not intended.

Screenshot of the issue using the default 'combat' tree:
![2023-06-19 17_43_05-Window](https://github.com/pufmat/skillsmod/assets/48658188/b9c84217-35bb-40c3-8faa-c6c779d90cb7)

**Comment by pufmat** [comment]
This is intended behavior.

**Comment by Sweenus** [comment]
The wiki seems to imply otherwise?
![Screenshot_2023-06-19-19-55-24-730-edit_com android chrome](https://github.com/pufmat/skillsmod/assets/48658188/0cf67eca-f7c2-4484-a0b6-9f1f1717e842)

**Comment by Sweenus** [comment]
Or I suppose this just means you can't start from another root skill.
I understand now, sorry.

I think it would make more sense for other roots to not be unlockable once one has been picked. But maybe that's just me.
