### ISSUE TITLE
I can't use attributes from another mod or from minecraft

### ISSUE THREAD

**Issue by LoloElSupremo** [pufmat/skillsmod#3]
![Capture](https://user-images.githubusercontent.com/58444534/232210882-04fd542f-8200-4dd5-8d49-ef70c41a3972.PNG)
Could not load config:
Expected a valid reward type at `type` at index 0 at `rewards` at `root_crit_chance+3%` at `categories\combat\definitions.json`
Could you make it possible?

**Comment by pufmat** [comment]
To use attributes as rewards set `type` to `puffish_skills:attribute`.

![obraz](https://user-images.githubusercontent.com/82769502/232216708-328ca85e-56e8-4c58-985b-9f2452eca56d.png)

**Comment by LoloElSupremo** [comment]
Thanks !
