### ISSUE TITLE
'Dummy' reward type usage

### ISSUE THREAD

**Issue by Sweenus** [pufmat/skillsmod#31]
Hi there 👋

I've just updated Simply Skills to 1.20.1 and have noticed that there has been a dummy reward type added to the latest version of Puffish Skills.
Is this currently usable in the definitions file? If so, do you have an example of its usage you could provide?

Cheers,

**Comment by pufmat** [comment]
This reward type does nothing :laughing:. It can't be used in json. 

It is internally used when a reward marked as not required fails to load (e.g. attribute does not exist). Furthermore, it is also possible to create not required conditions and parameters. 

Thanks to this issue I realized that I forgot to cover this topic in the wiki.

**Comment by Sweenus** [comment]
Ooooh, I see - I thought from the phrasing that it might have been a rewardless skill (This would be useful for my particular usecase).
Thank you for the explanation 🙂
