### ISSUE TITLE
getUnlockedSkills replacement

### ISSUE THREAD

**Issue by Sweenus** [pufmat/skillsmod#32]
Hi there 👋 

With the removal of getUnlockedSkills from the API in the latest version, is there an alternate way I can access this information?

**Comment by pufmat** [comment]
Use `SkillsAPI.getCategory(...)` and then `Category.getUnlockedSkills(...)`.

**Comment by Sweenus** [comment]
> Use `SkillsAPI.getCategory(...)` and then `Category.getUnlockedSkills(...)`.

Perfect! Thank you 🙂

**Comment by Sweenus** [comment]
Sorry for all the questions.
Is there an easy way to match a skill against the definitions/skills file?

Previously, getUnlockedSkills returned the literal IDs found in the Skills.json, which allowed me to create an index of public strings I could access to execute player abilities when specific skills were unlocked.

This is no longer the case and I'm not too sure how to convert the ouptut of getUnlockedSkills into something I can match against the Definitions.json or Skills.json.

**Comment by pufmat** [comment]
To get ID like in the old API you can call `Skill.getId()`. 

If you have more questions you can message me on Discord, my username is `pufmat`.

**Comment by Sweenus** [comment]
Thank you! That sent me down the right path and I have it all working now.
And thank you for offering a direct line of communication. I've felt a little bad spamming your issue tracker like this 🙂
