### ISSUE TITLE
mismatch

### ISSUE THREAD

**Issue by Rogenar** [pufmat/skillsmod#33]
![wss1](https://github.com/pufmat/skillsmod/assets/122460325/b38a26c3-a88f-49f2-a13d-9ecdd11f3df4)
[latest.log](https://github.com/pufmat/skillsmod/files/12253446/latest.log)

**Comment by pufmat** [comment]
This is because SimplySkills requires older version of my mod. You can download the older version of Pufferfish's Skills or ask the author of SimplySkills to update their mod.
