### ISSUE TITLE
More expression options

### ISSUE THREAD

**Issue by jouki** [pufmat/skillsmod#35]
Hello,

would be please possible to implement the modulo (%) operator? (most important one)

-----
plus several questions that are a bit off-topic:
1. Is it possible to somehow make a skill tree that unlocks after completing one?
2. Is there a discord or community where others can ask for help?
3. I have a warning that I'm not sure why I'm getting:
```
[19:40:54] [Server thread/WARN] [puffish_skills/]: [puffish_skills] Expression returned a value that is not finite at `expression` at `data` at `experience_per_level` at `categories\combat\experience.json`
```

my formula:
(experience per level)
`"expression": "((level ^ 3) / (level * 1.05)) + 200"`

(sources - experience)
`"expression": "dropped_xp + max_health / 5"`

**Comment by pufmat** [comment]
> would be please possible to implement the modulo (%) operator?

Yeah, I can add modulo. I'll leave this issue open until it is added.

> Is it possible to somehow make a skill tree that unlocks after completing one?

There is currently no way to do this easily without using API. But it should be possible to use command reward and some mcfunctions.

> Is there a discord or community where others can ask for help?

I created it today: https://discord.gg/F4EKxzW4hf

> I have a warning that I'm not sure why I'm getting:

This is because `level` starts from 0, and the expression you provided is undefined (due to division by 0) when `level` is 0.

**Comment by jouki** [comment]
> Yeah, I can add modulo. I'll leave this issue open until it is added.

Thank you ❤️

> There is currently no way to do this easily without using API. But it should be possible to use command reward and some mcfunctions.

Unfortunately, I have no experience with any scripting/coding in Minecraft whatsoever. but would bi nice to have sort of advancing in skill trees

> This is because level starts from 0, and the expression you provided is undefined (due to division by 0) when level is 0.

I'm getting this message all the time even though already have tens of levels done already.
