### ISSUE TITLE
Sometimes Invalid Player Data, but mostly Cannot invoke "net.minecraft.resources.ResourceLocation.toString()" because "p_130086_" 

### ISSUE THREAD

**Issue by NoruRama** [pufmat/skillsmod#39]
Hello, it's quite difficult to say what exactly the error is, but it seems like the main reason is: [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "net.minecraft.resources.ResourceLocation.toString()" because "p_130086_" is null

It's happened after I was reloading and changing some definitions for new attributes on a server, while changing I wasn't noticing anything but server froze... strangely you could continue to play while on server but
1. Pufferfish's Skills doesn't open and doesn't give errors, I think?
2. I got kicked after some time or server restarted after some time for no reason?
3. now I cannot join the server because of another error ([de.teamlapen.lib.network.ClientboundUpdateEntityPacket/]: There is nothing to update for entity ServerPlayer['Dimas13'/39, l='ServerLevel[world]', x=39.50, y=65.00, z=-35.50, removed=UNLOADED_WITH_PLAYER](Dimas13 at 39.5,65.0,-35.5))

if it has ERRORS in config for definition and others, then nothing is happening and server working fine

Server Logs: 
1. "Reloaded with ./reload while being on server" :
[latest1.log](https://github.com/pufmat/skillsmod/files/12503835/latest1.log)

2. "After server restart after 1 Log and trying to join" :
[latest2.log](https://github.com/pufmat/skillsmod/files/12503836/latest2.log)

Client Logs: Nothing happened? But still if it somehow helps
[latest.log](https://github.com/pufmat/skillsmod/files/12503844/latest.log)

ModPack on server: (Sorry if modpack is big)
[Mods.txt](https://github.com/pufmat/skillsmod/files/12503858/Mods.txt)

Thank you if you could somehow help with our problem

**Comment by NoruRama** [comment]
Also, Config that I'm was going to use for testing and was trying to transfer to server, maybe it can help with finding problem (just changed to .txt because no support file type)

[config.txt](https://github.com/pufmat/skillsmod/files/12514701/config.txt)
[connections.txt](https://github.com/pufmat/skillsmod/files/12514713/connections.txt)
[definitions.txt](https://github.com/pufmat/skillsmod/files/12514714/definitions.txt)
[experience.txt](https://github.com/pufmat/skillsmod/files/12514715/experience.txt)
[skills.txt](https://github.com/pufmat/skillsmod/files/12514716/skills.txt)
[category.txt](https://github.com/pufmat/skillsmod/files/12514717/category.txt)

Absolute new config is not crushing server or kicking a player, but adding another language (Russian for Title, Description or Category) is for some reason doing it... 
But after removing everything back to English, it still doesn't work.

**Comment by pufmat** [comment]
This is because your category name is `FighterTraining`, but allowed characters are only lowercase letters and underscore. It is still a bug as it should result in config error instead of a crash.

**Comment by NoruRama** [comment]
That was strange, but after fixing category name, server worked normally not restarting and player can open skill tree without errors in console.

Big thanks to you and your team for mod )
