### ISSUE TITLE
Crash with new connection

### ISSUE THREAD

**Issue by LoloElSupremo** [pufmat/skillsmod#4]
Hi, I made a new skills and connections file on your online editor but now when I try to join a world or create one I crash
Crash report : https://pastebin.com/YmBt1uVm
Log : https://pastebin.com/QxTk7Pm5

Waiting for a response, thank you!

**Comment by pufmat** [comment]
Have you created any unconnected skills? If you can please send your config files.

**Comment by LoloElSupremo** [comment]
Ah I see, indeed I had put a skill not connected to the rest. Thank you I was able to solve my problem!

**Comment by pufmat** [comment]
Unconnected skills should not cause crash. It will be fixed.

**Comment by pufmat** [comment]
Fixed in 0.1.2
