### ISSUE TITLE
Mismatched Mod Channel List

### ISSUE THREAD

**Issue by NonProgrammerCharacter** [pufmat/skillsmod#47]
When joining my server with only this mod installed I get the following error "Mismatched Mod Channel List".

All Versions are identical on Server and Client.

Minecraft Version:
1.20.2
Forge Version:
48.0.30
Mod Version:
0.9.0-1.20.2-forge

Only usable entry in Log I could find is: 
[Netty Client IO #0/ERROR] [ne.mi.ne.NetworkRegistry/NETREGISTRY]: Channels [puffish_skills:show_category, puffish_skills:points_update, puffish_skills:experience_update, puffish_skills:skill_unlock, puffish_skills:invalid_config, puffish_skills:hide_category] rejected their server side version number during listping
[Netty Client IO #2/ERROR] [ne.mi.ne.NetworkRegistry/NETREGISTRY]: Channels [puffish_skills:show_category,puffish_skills:points_update,puffish_skills:experience_update,puffish_skills:skill_unlock,puffish_skills:invalid_config,puffish_skills:hide_category] rejected their server side version number

I have reinstalled the mod multiple times on server and client without any change to the error message.

**Comment by pufmat** [comment]
Thanks for reporting. Fixed in version 0.10.1.
