### ISSUE TITLE
Line breaks broken in the last update

### ISSUE THREAD

**Issue by nvb-uy** [pufmat/skillsmod#55]
I used to add new lines by just using \n in the skill definition, but as of 0.10.0, the line breaks now do not work an instead show a LF symbol

![img](https://cdn.discordapp.com/attachments/1010666451876724806/1171840535544205404/image.png)

**Comment by Sweenus** [comment]
You need to split out your title & description fields, line breaks function correctly in the description. I had to do this for 5000 lines of json when I updated Simply Skills :')

Example:
```
		"title": "Path of the §bWayfarer",
		"description": "§a+10% §f[x]§7 Movement Speed",
		"frame": "challenge",
		"icon": {
```

**Comment by nvb-uy** [comment]
I see, thank you sweeney!!!!
