### ISSUE TITLE
SUGGESTION : display position and zoom of the skill screen to be keeped

### ISSUE THREAD

**Issue by TwelveYO21** [pufmat/skillsmod#63]
As the title. It is quite annoying to adjust the display each time when the screen is opened frequently.

**Comment by Chad90b** [comment]
agreed it would be nice for the default zoom to be altered or configurable and for the client to remember which zoom-level the skills screen was left on when you re-open the skills tree.
same with the tabs; would be a good qol improvement if the client also remembered which tab you were on last when you re-open the skill stree.

**Comment by pufmat** [comment]
Implemented in 0.13.0.
