### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by yahi-ko** [pufmat/skillsmod#64]
Crash: https://paste.ee/p/2C5Id

Minecraft 1.20.1
Fabric Loader: 0.15.3
Fabric API: 0.91.0+1.20.1

Fabric Mods: 
		adaptive-tooltips: Adaptive Tooltips 1.3.0
		advancementplaques: Advancement Plaques 1.4.11
		alloy_forgery: Alloy Forgery 2.1.2+1.20
		alternate-current: Alternate Current 1.7.0
		ambientenvironment: Ambient Environment 11.0.0.1
		arc: Arc 1.4.1
		archers: Archers (RPG Series) 1.0.6+1.20.1
		architectury: Architectury 9.1.12
		autohud: Auto HUD 6.3.3+1.20.1
		azurelib: AzureLib 2.0.18
		azurelibarmor: AzureLib Armor 2.0.3
		badoptimizations: BadOptimizations 1.5.0
		balm-fabric: Balm 7.2.1
		bbca: Blackwing's Better Combat Addon 1.0.0
		bclib: BCLib 3.0.14
		bedbenefits: BedBenefits 13.0.2
		betterbeds: Better Beds 1.3.0
		betterchunkloading: Better chunk loading mod 1.20.1-2.6
		betterclouds: Better Clouds 1.3.13+1.20.1
		bettercombat: Better Combat 1.8.3+1.20.1
		betterend: Better End 4.0.11
		betterfpsdist: Better FPS distance Mod 1.20.1-4.0
		betternether: Better Nether 9.0.10
		blanket-client-tweaks: Blanket Client-tweaks 1.1.4
		bookshelf: Bookshelf 20.1.8
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.7.5-1.20.1
		botarium: Botarium 2.2.1
		cardinal-components: Cardinal Components API 5.2.2
		casualness_delight: Casualness Delight Fabric 1.20.1-0.3a
		chatanimation: ChatAnimation 1.0.5
		chunksending: Chunksending Mod 1.20.1-2.8
		clientcrafting: clientcrafting Mod 1.20.1-1.7
		cloth-config: Cloth Config v11 11.1.118
		clumps: Clumps 12.0.0.3
		clutter: Clutter 1.20-0.5.5
		cobblemon: Cobblemon 1.4.1+1.20.1
		combatroll: Combat Roll 1.3.0+1.20.1
		connectivity: Connectivity Mod 1.20.1-4.9
		coroutil: CoroUtil 1.20.1-1.3.5
		create: Create 0.5.1-d-build.5+mc1.20.1
		create_new_age: Create: New Age 1.1.1
		cristellib: Cristel Lib 1.1.5
		culturalcreators: Cultural Creators 1.0.0
		culturaldelights: Cultural Delights Fabric 0.14.11+1.20.1
		cupboard: cupboard 1.20.1-2.2
		deeperdarker: Deeper and Darker 1.2.5
		desolation: Desolation 1.3.2
		dungeon_difficulty: Dungeon Difficulty 2.0.5+1.20.1
		dynamic_fps: Dynamic FPS 3.3.2
		dynamiccrosshair: Dynamic Crosshair 7.4.2+1.20
		dynamiccrosshaircompat: Dynamic Crosshair Compat 3.7.1+1.20.1
		dynview: Dynamic View Mod 1.20.1-3.2
		eco: Ecospherical Expansion 2.4.1
		enchdesc: EnchantmentDescriptions 17.0.11
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20.1
		epherolib: EpheroLib 1.2.0
		epicsamurai: EpicSamurai-Fabric 0.0.2-beta
		equipmentcompare: Equipment Compare 1.3.8
		eugenes_guan_dao: Eugene's Guan Dao 1.0.0
		everycomp: Every Compat 1.20-2.6.21
		fabric-api: Fabric API 0.91.0+1.20.1
		fabric-language-kotlin: Fabric Language Kotlin 1.10.17+kotlin.1.9.22
		fabricloader: Fabric Loader 0.15.3
		fakerlib: fakerlib 0.1.0
		fallingtree: FallingTree 4.3.3
		farmersdelight: Farmer's Delight 1.20.1-1.4.3
		farsight: Farsight Mod 1.20.1-4.2
		fastasyncworldsave: fastasyncworldsave Mod 1.20.1-1.2
		faster_entity_animations: FastAnim 1.6
		fastload: Fast Load 3.4.0
		ferritecore: FerriteCore 6.0.1
		fog-looks-good-now: FogLooksGoodNow 2.1.0+1.20.1
		forgeconfigapiport: Forge Config API Port 8.0.0
		framework: Framework 0.6.16
		frozenlib: FrozenLib 1.5.4-Fabric+1.20.1
		fzzy_core: Fzzy Core 0.3.4+1.20.1
		galosphere: Galosphere 1.20.1-1.4.1
		galospheretrimming: Galosphere Trimming 1.20.1-1.0.0-quilt
		gear_core: Gear Core 0.3.7+1.20.1
		gearifiers: Gearifiers 0.5.2+1.20.1
		go-fish: Go Fish 1.6.3+1.20.1
		gpumemleakfix: Gpu memory leak fix mod 1.20.1-1.8
		iceberg: Iceberg 1.1.18
		immediatelyfast: ImmediatelyFast 1.2.8+1.20.4
		indium: Indium 1.0.27+mc1.20.1
		inventoryessentials: Inventory Essentials 8.2.1
		iris: Iris 1.6.11
		itemborders: Item Borders 1.2.1
		itemrestrictions: Item Restrictions 1.1.2
		jade: Jade 11.7.0
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 15.2.0.27
		jobsplus: Jobs+ 1.3
		knavesneeds: Knaves' Needs 2.0.1+1.20.1
		krypton: Krypton 0.2.3
		lambdynlights: LambDynamicLights 2.3.2+1.20.1
		lazy-language-loader: lazy-language-loader 0.3.3
		lazydfu: LazyDFU 0.1.3
		leaky: leaky Mod 1.20.1-1.6
		letmedespawn: Let Me Despawn 1.2.0
		levelz: LevelZ 1.4.12
		libz: LibZ 1.0.3
		lithium: Lithium 0.11.2
		logbegone: Log Begone 1.0.8
		magic_vibe_decorations: Magic Vibe Decorations 1.7.0
		majruszlibrary: Majrusz Library 7.0.3
		majruszsaccessories: Majrusz's Accessories 1.4.0
		majruszsenchantments: Majrusz's Enchantments 1.10.5
		map_atlases: Map Atlases 1.20-2.7.6
		maxhealthfix: MaxHealthFix 12.0.2
		mcda: MC Dungeons Armors 5.0.1
		mcdar: MC Dungeons Artifacts 3.0.0
		mcde: MC Dungeons: Enchanting 1.5.4.1-1.20
		mcdw: MC Dungeons Weapons 8.1.0
		mcwlights: Macaw's Lights and Lamps 1.0.6
		memoryleakfix: Memory Leak Fix 1.1.2
		midnightlib: MidnightLib 1.4.1
		minecells: Mine Cells 1.6.1
		minecraft: Minecraft 1.20.1
		modernfix: ModernFix 5.11.1+mc1.20.1
		modmenu: Mod Menu 7.2.2
		moonlight: Moonlight 1.20-2.8.79
		moreculling: More Culling 1.20.1-0.19.0
		morecullingextra: More Culling Extra 1.1-1.20.1
		moremobs: More Mobs 1.5.1+mod
		mousetweaks: Mouse Tweaks 2.25
		mru: Mineblock's Repeated Utilities 0.4.0+1.20
		mythicmetals: Mythic Metals 0.19.2+1.20.1
		mythicmobs: Mythic Mobs 1.20.1-connector-1.4.5
		nature_arise: Nature Arise 0.6.0B
		netherportalfix: NetherPortalFix 13.0.1
		numismatic-overhaul: Numismatic Overhaul 0.2.12+1.20.1
		owo: o?o 0.11.2+1.20
		paladins: Paladins & Priests (RPG Series) 1.0.4+1.20.1
		patchouli: Patchouli 1.20.1-84-FABRIC
		pehkui: Pehkui 3.7.12+1.14.4-1.20.4
		placeable_food: 3D placeable food 1.2.0
		player-animator: Player Animator 1.0.2-rc1+1.20
		prism: Prism 1.0.5
		projectile_damage: Projectile Damage Attribute 3.2.2+1.20.1
		puffish_skills: Pufferfish's Skills 0.11.0
		recipeessentials: recipeessentials Mod 1.20.1-3.2
		repurposed_structures: Repurposed Structures 7.1.11+1.20.1-fabric
		resourcefulconfig: Resourcefulconfig 2.1.1
		resourcefullib: Resourceful Lib 2.1.20
		runes: Runes 0.9.10+1.20.1
		simplyswords: Simply Swords 1.51.5-1.20.1
		snowyspirit: Snowy Spirit 1.20-3.0.3
		snuffles: Snuffles 1.0.0+1.20
		sodium: Sodium 0.5.3
		spell_engine: Spell Engine 0.12.4+1.20.1
		spell_power: Spell Power Attribute 0.9.19+1.20.1
		spellbladenext: Spellblades and Such 1.3
		starlight: Starlight 1.1.2+fabric.dbc156f
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.16
		supplementaries: Supplementaries 1.20-2.7.20
		suppsquared: Supplementaries Squared 1.20-1.1.12
		t_and_t: Towns and Towers 1.12
		tempad: Tempad 2.3.1
		tempest: Tempest 0.1.7
		terrablender: TerraBlender 3.0.0.169
		the_bumblezone: The Bumblezone - Fabric 7.1.14+1.20.1-fabric
		thekatanasmod: The Katana's Mod 1.1.1
		travel_friendly_food: Travel friendly food 1.0.0
		tridents_n_stuff: Tridents 'n' Stuff 0.1.1+1.20.1
		trinkets: Trinkets 3.7.1
		twigs: Twigs 3.1.0
		uilib: UI Lib 0.2.11
		valentines_blessing: Valentine's Blessing 1.5.0
		vmp: Very Many Players 0.2.0+beta.7.102
		watut: What Are They Up To 1.20.1-1.0.12
		waystones: Waystones 14.1.3
		weaponmaster: YDM's Weapon Master 3.0.5
		wilderwild: Wilder Wild 2.2.3-Fabric+1.20.1
		wizards: Wizards (RPG Series) 1.0.4+1.20.1
		yet_another_config_lib_v3: YetAnotherConfigLib 3.2.1+1.20
		zenith: Zenith 1.0.0-1.20.1
		zenith_attributes: Zenith Attributes 0.1.2

**Comment by yahi-ko** [comment]
seems like its a problem with zenith and its requirements. encountered the crash after attacking a modded mob

**Comment by TheWinABagel** [comment]
It is in fact a problem with zenith, will be fixed in the next version of zenith attributes

**Comment by yahi-ko** [comment]
Fixed now
