### ISSUE TITLE
Crash after opening skill tree

### ISSUE THREAD

**Issue by steini0101** [pufmat/skillsmod#66]
Every time im opening the skills screen with pressing the button the game freezes and crashes afterwords. 
Playing Forge 1.20.1 with other mods

**Comment by MissMagz** [comment]
did you ever find a fix for this? everyone in my server is crashing when they open the skill tree. im running 1.20.1 aswell

**Comment by Lstriker8D8** [comment]
I'm dealing with the same issue as well. I listed a crash report here to be of more help to the mod author
[crash-2024-01-13_13.58.29-client.txt](https://github.com/pufmat/skillsmod/files/13929198/crash-2024-01-13_13.58.29-client.txt)

**Comment by Pitatt0** [comment]
I got the same issue, and im using minecraft 1.20.1 aswell, its my own modpack

**Comment by pemelyanov** [comment]
I got same, game crashes only on server. In single player i got artifact when oppening skill tree (black borders on screen). It causes only when Optifine is installed.

**Comment by pufmat** [comment]
It is caused be an incompatibility with OptiFine which was recently fixed in mod version 0.11.3. Updating to that version should fix the problem.
