### ISSUE TITLE
Not Urgent, Typo in docs

### ISSUE THREAD

**Issue by KaziiTheAvali** [pufmat/skillsmod#67]
in [Root Skills](https://puffish.net/skillsmod/docs/configuration/roots) one is spelled on. this is not an urgent problem, i am just pointing it out incase you didnt know.
![image](https://github.com/pufmat/skillsmod/assets/87594664/760494eb-55b4-4708-99aa-081db819eb35)

**Comment by pufmat** [comment]
Fixed.
