### ISSUE TITLE
need help with experience.json

### ISSUE THREAD

**Issue by AsheX1** [pufmat/skillsmod#69]
im trying to combine combat and mining in to 1 files for a single skill tree

i have this at the time but only mining gives XP modded ore does not give anything combat give 0 XP now and im kinda at a loss where i add ores to get XP from them and how i disable silk touch XP
`{
	"experience_per_level": {
		"type": "expression",
		"data": {
			"expression": "min(level ^ 1.0 + 50, 250)"
		}
	},
	"sources": [
		{
			"type": "puffish_skills:kill_entity",
			"data": {
				"parameters": {
					"dropped_xp": {
						"type": "entity_dropped_experience"
					},
					"max_health": {
						"type": "entity_max_health"
					}
				},
				"experience": [
					{
						"expression": "dropped_xp + max_health / 20"
					}
				],
				"anti_farming": {
					"limit_per_chunk": 20,
					"reset_after_seconds": 300
				}
			},
           	"type": "puffish_skills:mine_block",
			"data": {
				"conditions": {
					"silk_touch": {
						"type": "tool_nbt",
						"data": {
							"nbt": "{Enchantments:[{id:\"minecraft:silk_touch\"}]}"
						}
					},
					"stone_like": {
						"type": "block_tag",
						"data": {
							"tag": "base_stone_overworld"
						}
					},
					"deepslate": {
						"type": "block",
						"data": {
							"block": "deepslate"
						}
					},
					"coal_ore": {
						"type": "block",
						"data": {
							"block": "coal_ore"
						}
					},
					"copper_ore": {
						"type": "block",
						"data": {
							"block": "copper_ore"
						}
					},
					"iron_ore": {
						"type": "block",
						"data": {
							"block": "iron_ore"
						}
					},
					"gold_ore": {
						"type": "block",
						"data": {
							"block": "gold_ore"
						}
					},
					"redstone_ore": {
						"type": "block",
						"data": {
							"block": "redstone_ore"
						}
					},
					"lapis_ore": {
						"type": "block",
						"data": {
							"block": "lapis_ore"
						}
					},
					"diamond_ore": {
						"type": "block",
						"data": {
							"block": "diamond_ore"
						}
					},
					"emerald_ore": {
						"type": "block",
						"data": {
							"block": "emerald_ore"
						}
					},
					"deepslate_coal_ore": {
						"type": "block",
						"data": {
							"block": "deepslate_coal_ore"
						}
					},
					"deepslate_copper_ore": {
						"type": "block",
						"data": {
							"block": "deepslate_copper_ore"
						}
					},
					"deepslate_iron_ore": {
						"type": "block",
						"data": {
							"block": "deepslate_iron_ore"
						}
					},
					"deepslate_gold_ore": {
						"type": "block",
						"data": {
							"block": "deepslate_gold_ore"
						}
					},
					"deepslate_redstone_ore": {
						"type": "block",
						"data": {
							"block": "deepslate_redstone_ore"
						}
					},
					"deepslate_lapis_ore": {
						"type": "block",
						"data": {
							"block": "deepslate_lapis_ore"
						}
					},
					"deepslate_diamond_ore": {
						"type": "block",
						"data": {
							"block": "deepslate_diamond_ore"
						}
					},
					"deepslate_emerald_ore": {
						"type": "block",
						"data": {
							"block": "deepslate_emerald_ore"
						}
					}
				},
				"experience": [
					{
						"condition": "!silk_touch & stone_like",
						"expression": "1"
					},
					{
						"condition": "!silk_touch & deepslate",
						"expression": "2"
					},
					{
						"condition": "!silk_touch & (coal_ore | copper_ore | iron_ore | gold_ore | redstone_ore | lapis_ore | diamond_ore | emerald_ore)",
						"expression": "10"
					},
					{
						"condition": "!silk_touch & (deepslate_coal_ore | deepslate_copper_ore | deepslate_iron_ore | deepslate_gold_ore | deepslate_redstone_ore | deepslate_lapis_ore | deepslate_diamond_ore | deepslate_emerald_ore)",
						"expression": "12"
					}
				]
			}
		}
	]
}`

so i need to get combat XP working again
and add ores in here and stop silk touch XP

**Comment by AsheX1** [comment]
oh god github code is still shit 
here is a pastebin https://pastebin.com/Ce28dpbd

**Comment by pufmat** [comment]
Sorry for the late replay. You have made a mistake, it should be like that:
```json
{
    "experience_per_level": {
        "type": "expression",
        "data": {
            "expression": "min(level ^ 1.0 + 50, 250)"
        }
    },
    "sources": [
        {
            "type": "puffish_skills:kill_entity",
            "data": {
                "parameters": {
                    "dropped_xp": {
                        "type": "entity_dropped_experience"
                    },
                    "max_health": {
                        "type": "entity_max_health"
                    }
                },
                "experience": [
                    {
                        "expression": "dropped_xp + max_health / 20"
                    }
                ],
                "anti_farming": {
                    "limit_per_chunk": 20,
                    "reset_after_seconds": 300
                }
            }
        },
        {
            "type": "puffish_skills:mine_block",
            "data": {
                "conditions": {
                    "silk_touch": {
                        "type": "tool_nbt",
                        "data": {
                            "nbt": "{Enchantments:[{id:\"minecraft:silk_touch\"}]}"
                        }
                    },
                    "stone_like": {
                        "type": "block_tag",
                        "data": {
                            "tag": "base_stone_overworld"
                        }
                    },
                    "deepslate": {
                        "type": "block",
                        "data": {
                            "block": "deepslate"
                        }
                    },
                    "coal_ore": {
                        "type": "block",
                        "data": {
                            "block": "coal_ore"
                        }
                    },
                    "copper_ore": {
                        "type": "block",
                        "data": {
                            "block": "copper_ore"
                        }
                    },
                    "iron_ore": {
                        "type": "block",
                        "data": {
                            "block": "iron_ore"
                        }
                    },
                    "gold_ore": {
                        "type": "block",
                        "data": {
                            "block": "gold_ore"
                        }
                    },
                    "redstone_ore": {
                        "type": "block",
                        "data": {
                            "block": "redstone_ore"
                        }
                    },
                    "lapis_ore": {
                        "type": "block",
                        "data": {
                            "block": "lapis_ore"
                        }
                    },
                    "diamond_ore": {
                        "type": "block",
                        "data": {
                            "block": "diamond_ore"
                        }
                    },
                    "emerald_ore": {
                        "type": "block",
                        "data": {
                            "block": "emerald_ore"
                        }
                    },
                    "deepslate_coal_ore": {
                        "type": "block",
                        "data": {
                            "block": "deepslate_coal_ore"
                        }
                    },
                    "deepslate_copper_ore": {
                        "type": "block",
                        "data": {
                            "block": "deepslate_copper_ore"
                        }
                    },
                    "deepslate_iron_ore": {
                        "type": "block",
                        "data": {
                            "block": "deepslate_iron_ore"
                        }
                    },
                    "deepslate_gold_ore": {
                        "type": "block",
                        "data": {
                            "block": "deepslate_gold_ore"
                        }
                    },
                    "deepslate_redstone_ore": {
                        "type": "block",
                        "data": {
                            "block": "deepslate_redstone_ore"
                        }
                    },
                    "deepslate_lapis_ore": {
                        "type": "block",
                        "data": {
                            "block": "deepslate_lapis_ore"
                        }
                    },
                    "deepslate_diamond_ore": {
                        "type": "block",
                        "data": {
                            "block": "deepslate_diamond_ore"
                        }
                    },
                    "deepslate_emerald_ore": {
                        "type": "block",
                        "data": {
                            "block": "deepslate_emerald_ore"
                        }
                    }
                },
                "experience": [
                    {
                        "condition": "!silk_touch & stone_like",
                        "expression": "1"
                    },
                    {
                        "condition": "!silk_touch & deepslate",
                        "expression": "2"
                    },
                    {
                        "condition": "!silk_touch & (coal_ore | copper_ore | iron_ore | gold_ore | redstone_ore | lapis_ore | diamond_ore | emerald_ore)",
                        "expression": "10"
                    },
                    {
                        "condition": "!silk_touch & (deepslate_coal_ore | deepslate_copper_ore | deepslate_iron_ore | deepslate_gold_ore | deepslate_redstone_ore | deepslate_lapis_ore | deepslate_diamond_ore | deepslate_emerald_ore)",
                        "expression": "12"
                    }
                ]
            }
        }
    ]
}
```

**Comment by AsheX1** [comment]
aaaa oke thank
