### ISSUE TITLE
Unsure if this is related but here goes.

### ISSUE THREAD

**Issue by NattoRiisa** [pufmat/skillsmod#7]
Online editor for this mod is offline!

![image](https://user-images.githubusercontent.com/52566765/235279486-f50334a6-82be-41a8-bea1-d16c2da24180.png)

**Comment by pufmat** [comment]
Thanks for reporting. I can't reproduce this, please check if the issue still persists.

**Comment by NattoRiisa** [comment]
![image](https://github.com/pufmat/skillsmod/assets/52566765/b5e44bfe-eaf6-41bb-b75f-561ff550e543)
it appears to still persist

~~i think its a browser-related issue??~~

Doesn't work on Chrome (With no extensions)

**Comment by NattoRiisa** [comment]
> ![image](https://user-images.githubusercontent.com/52566765/238193486-b5e44bfe-eaf6-41bb-b75f-561ff550e543.png) it appears to still persist
> 
> ~i think its a browser-related issue??~
> 
> Doesn't work on Chrome (With no extensions)

Tried to manually put https://
nothing happened

i don't know why this happened for me :<

**Comment by NattoRiisa** [comment]
can you send the exact link for the site? i wanna double check ;w;

**Comment by pufmat** [comment]
https://puffish.net/skillsmod/editor/

I think I have found the source of the problem. My current DNS hosting provider is trash so the website is not available in all countries. I'll change it soon. Sorry for inconvenience.

**Comment by NattoRiisa** [comment]
alright! I hope you find a better DNS provider!

**Comment by pufmat** [comment]
DNS changed, problem should be resolved.
