### ISSUE TITLE
Weird issue ( 2 explanations and two different )

### ISSUE THREAD

**Issue by TvplayerGH** [pufmat/skillsmod#73]
1. I get into a game with like 99 mods including skills mod. I press the button to open the menu it glitches and shows me a golden sword left of my screen
2. I get into a hardcore world open the skill menu and see the menu but the game crashes right after with no codes only error code -805306369
( ALSO it says its an entity ) I'll also show u the list of mods and the version I'm playing one
Minecraft 1.20.1
Forge 1.20.1-forge-47.2.20

![image_2024-02-03_045142128](https://github.com/pufmat/skillsmod/assets/157854822/9a35f140-d01c-4d86-a35f-52a60e2ec2af)

**Comment by pufmat** [comment]
It is caused be an incompatibility with OptiFine which was recently fixed in mod version 0.11.3. Updating to that version should fix the problem.
