### ISSUE TITLE
OptiFine incompatibility

### ISSUE THREAD

**Issue by eSqadron** [pufmat/skillsmod#74]
MC 1.20.1
Forge 47.2.0
Puffish skills 0.11.2
OptiFine HD U I6

Upon clicking k to open skill tree, game crashes.

Crash log: [CrashLog.txt](https://github.com/pufmat/skillsmod/files/14150791/CrashLog.txt)

**Comment by pufmat** [comment]
Fixed in mod version 0.11.3.
