### ISSUE TITLE
[BUG] Error whjile loading on server Fabric 1.20.4

### ISSUE THREAD

**Issue by Tresillo2017** [pufmat/skillsmod#76]
# Error log
https://pastebin.com/raw/tNGQxFHM

# Crash log
https://pastebin.com/raw/WBa7EhpN

**Comment by pufmat** [comment]
I have incorrectly set game version for that mod file while uploading. I have just fixed it, please download again corresponding mod file for 1.20.4. Sorry for the inconvenience.
