### ISSUE TITLE
Loading any type of world leads to crash of the game

### ISSUE THREAD

**Issue by jmichnaa** [pufmat/skillsmod#77]
I just installed the puffish_skills-0.11.3-1.20.2-fabric because it just looked fantastic. After starting the game and trying to load my survival World, it starts by saying "loading resources", this goes away after 2 or 3 seconds and then the screen freezes. The OpenJDK is not responding and the game crashes if i'm trying to click my mousebutton. I tried giving the JavaSDK more Ram and very high priority. But after using around 1gb of my 32gb (DDR4) it just stops responding and the game needs to restart with the following Problem:
![FirstError](https://github.com/pufmat/skillsmod/assets/126777199/69558514-05ff-44b7-8adf-040a4dc9064d)
![MCScreenTypeOfError](https://github.com/pufmat/skillsmod/assets/126777199/69bcebb0-fcae-4cbe-8c54-add77d4cab5b)
I was searching the Internet for some help but didn't find any that worked tho. So this is my last try, maybe some of you guys can help me with this problem because i'd really like to try this mob, it would enhance my MC experience by a lot :)

**Comment by jmichnaa** [comment]
[crash-2024-02-23_19.08.49-server.txt](https://github.com/pufmat/skillsmod/files/14388927/crash-2024-02-23_19.08.49-server.txt)
Maybe this crash report helps!

**Comment by jmichnaa** [comment]
[latest.log](https://github.com/pufmat/skillsmod/files/14388963/latest.log)
And here is my "latest" log file

**Comment by pufmat** [comment]
I have incorrectly set game version for that mod file while uploading. I have just fixed it, please download again corresponding mod file for 1.20.4. Sorry for the inconvenience.
