### ISSUE TITLE
Your mods for newest minecraft and neoforge are incompatible

### ISSUE THREAD

**Issue by krjencik** [pufmat/skillsmod#81]
Minecraft 1.20.4 neoforge 20.4.211

![PuffishModError](https://github.com/pufmat/skillsmod/assets/92643141/6b1e25db-aefc-449f-bcb7-8146db8a8f17)

**... and there are just one version per mod.**

**Comment by pufmat** [comment]
The incompatibility error is intended, because every version of Pufferfish's Skills below 0.12.0 includes everything that Pufferfish's Attributes adds. However, version 0.12.0 of Pufferfish's Skills, when released, will no longer contain Pufferfish's Attributes, therefore they will be compatible.
