### ISSUE TITLE
Pufferpush skill icons disappeared

### ISSUE THREAD

**Issue by Anonyku05** [pufmat/skillsmod#84]
I have the latest version of the mod to date (0.11.5) in 1.20.4 fabric, and i have this weird visual bug where the sword and pickaxe icon are blank, same for other icons, look at the screens below:

![2024-04-04_15 31 46](https://github.com/pufmat/skillsmod/assets/48128391/daa71ab1-140a-4d17-82e5-53745a399b01)
![2024-04-04_15 32 01](https://github.com/pufmat/skillsmod/assets/48128391/b4353fb9-ccda-4bc3-b0c4-b0d47e7b8e27)

**Comment by pufmat** [comment]
Please post your list of mods and shaders if any. It looks like the item rendering issue never ends. :rofl: It is always broken for someone. :smiling_face_with_tear:

**Comment by Anonyku05** [comment]
There you go, not using any shader btw:

**AdvancementPlaques-1.20.4-fabric-1.5.1.jar
AmbientSounds_FABRIC_v5.3.5_mc1.20.4.jar
apocalypse-1.1.1_1.20.3-1.20.4.jar
appleskin-fabric-mc1.20.3-2.5.1.jar
ArcaneLanterns-v20.4.1-1.20.4-Fabric.jar
architectury-11.1.17-fabric.jar
Armorful-2.1.0+1.20.4.jar
autosmeltenchant-1.3.2.jar
BadOptimizations-2.1.0.jar
BambooEverything-fabric-4.1.0+mc1.20.4.jar
BarteringStation-v20.4.1-1.20.4-Fabric.jar
bedrockbreakers-1.6.jar
betterbeds-1.3.0-1.19.3.jar
BetterFurnaces-1.20.4-1.0.2-fabric.jar
BetterSmithingTable-1.1.2-Fabric-1.20.4.jar
BetterThanMending-fabric-2.0.0.jar
bettertrims-2.2.3.jar
blur-3.2.0.jar
BOMD-1.8.2-1.20.4.jar
Bookshelf-Fabric-1.20.4-23.0.6.jar
borderless-mining-1.1.9+1.20.2.jar
c2me-fabric-mc1.20.4-0.2.0+alpha.11.65.jar
capes-1.5.3+1.20.2-fabric.jar
cardinal-components-api-5.4.0.jar
cavedweller-1.3.0.jar
cave_dust-1.4.1.jar
charmofundying-fabric-7.1.1+1.20.4.jar
cloth-config-13.0.121-fabric.jar
collective-1.20.4-7.40.jar
completeconfig-2.5.3.jar
configurablemobpotioneffects-1.20.4-3.3.jar
continuity-3.0.0-beta.4+1.20.2.jar
CosmeticArmor-1.20-1.6.0.jar
CraftableTotemOfUndying-1.20.4-1.6.6.jar
CreativeCore_FABRIC_v2.11.16_mc1.20.4.jar
cryingportals-1.20.4-2.7.jar
cycletitlescreensplash-1.20.4-1.2.jar
dark-loading-screen-1.6.14.jar
deathquotes-fabric-1.20.2-3.3.jar
Debugify-1.20.4+1.1.jar
deeperdarker-fabric-1.20.4-1.2.6.jar
DeleteWorldsToTrash-v20.4.0-1.20.4-Fabric.jar
DisableCustomWorldsAdvice-5.0.jar
DistantFriends-fabric-1.20.4-0.7.1.jar
DistinguishedPotions-v20.4.1-1.20.4-Fabric.jar
DynamicSurroundings-Fabric-1.20.4-0.3.3.jar
earlyloadingscreen-mc1.20.4-0.1.5-all.jar
EasyAnvils-v20.4.3-1.20.4-Fabric.jar
EasyMagic-v20.4.0-1.20.4-Fabric.jar
EchoChest-v20.4.1-1.20.4-Fabric.jar
elytratrims-fabric-2.1.1+1.20.4.jar
emissive-plugin-1.20.4-2.0.4-fabric.jar
EnchantingInfuser-v20.4.1-1.20.4-Fabric.jar
enchantmentcompat-1.4.0+1.20.3.jar
EnchantmentDescriptions-Fabric-1.20.4-20.0.2.jar
endercage-1.1.jar
EnderZoology-v20.4.3-1.20.4-Fabric.jar
endportalrecipe-1.20.4-5.2.jar
EnhancedVisuals_FABRIC_v1.6.9_mc1.20.4.jar
entityculling-fabric-1.6.4-mc1.20.4.jar
exordium-fabric-1.2.1-mc1.20.4.jar
explosive-enhancement-1.2.2-1.20.x.jar
extractpoison-1.20.4-3.3.jar
ExtremeSoundMuffler-3.45-fabric-1.20.4.jar
fabric-api-0.96.11+1.20.4.jar
fabric-experiencebugfix-1.20-2.jar
fabric-hammers-1.3.0.jar
fabric-language-kotlin-1.10.19+kotlin.1.9.23.jar
fabric-romod-1.20.3-1.2.8.jar
FactoryAPI-1.20.4-2.1.3-fabric.jar
fallingleaves-1.15.5+1.20.1.jar
ferritecore-6.0.3-fabric.jar
firstperson-fabric-2.3.4-mc1.20.4.jar
fishontheline-1.20.4-3.2.jar
FogLooksGoodNow-2.2.0+1.20.4.jar
forcecrawl-fabric-1.20-1.0.2.jar
ForgeConfigAPIPort-v20.4.3-1.20.4-Fabric.jar
friendsandfoes-fabric-mc1.20.4-2.0.10.jar
friendsandfoes-flowerymooblooms-fabric-mc1.20.4-2.0.1.jar
gamemenuremovegfarb-fabric-mc1.19.4-2.1.2.jar
geckolib-fabric-1.20.4-4.3.1.jar
giantspawn-1.20.4-5.0.jar
glassbreaker-fabric-1.4.0+1.20.jar
GlitchCore-fabric-1.20.4-1.0.0.58.jar
grind-enchantments-3.1.2+1.20.4.jar
grindstonesharpertools-1.20.4-3.5.jar
healingcampfire-1.20.4-5.3.jar
Iceberg-1.20.4-fabric-1.1.18.jar
IllagerInvasion-v20.4.2-1.20.4-Fabric.jar
ImmediatelyFast-Fabric-1.2.11+1.20.4.jar
indium-1.0.30+mc1.20.4.jar
inventoryhud.fabric.1.20.4-3.4.19.jar
InventoryProfilesNext-fabric-1.20.3-1.10.10.jar
IronChests-2.0.1.jar
IronDoorKey-FABRIC-1.20.4-1.0.jar
ironladders-1.20.4-2.1.51-fabric.jar
ItemBorders-1.20.2-fabric-1.2.1.jar
ItemPhysic_FABRIC_v1.7.0_mc1.20.4.jar
Jade-1.20.4-fabric-13.3.1.jar
jei-1.20.4-fabric-17.3.0.49.jar
keepmysoiltilled-1.20.4-2.2.jar
krypton-0.2.6.jar
language-reload-1.5.10+1.20.3.jar
lazydfu-0.1.3.jar
LeavesBeGone-v20.4.1-1.20.4-Fabric.jar
LetSleepingDogsLie-1.20.4-Fabric-1.2.0.jar
LevelTextFix-Fabric-1.20.4-10.0.3.jar
libIPN-fabric-1.20.3-4.0.2.jar
lithium-fabric-mc1.20.4-0.12.1.jar
loadingbackgrounds-1.1.0-fabric.jar
mcw-bridges-2.1.0-mc1.20.4fabric.jar
mcw-doors-1.1.0-mc1.20.4fabric.jar
mcw-fences-1.1.1-mc1.20.4fabric.jar
mcw-furniture-3.2.2-mc1.20.4fabric.jar
mcw-lights-1.0.6-mc1.20.4fabric.jar
mcw-paintings-1.0.5-1.20.4fabric.jar
mcw-paths-1.0.4fabric-mc1.20.4.jar
mcw-roofs-2.3.0-mc1.20.4fabric.jar
mcw-trapdoors-1.1.2-mc1.20.4fabric.jar
mcw-windows-2.2.1-mc1.20.4fabric.jar
midnightcontrols-1.9.4+1.20.4.jar
mineralchance-1.20.4-3.5.jar
Model-Gap-Fix-Mod-Fabric-1.20.4.jar
modernfix-fabric-5.15.0+mc1.20.4.jar
modmenu-9.0.0.jar
MoreChestVariants-1.5.0+1.20.4-Fabric.jar
moremcmeta-1.20.4-4.4.7-fabric.jar
MoT v1.1 - fabric 1.20.4.jar
mru-0.4.0+1.20.4.jar
music_control-1.7.1+1.20.4.jar
MutantMonsters-v20.4.1-1.20.4-Fabric.jar
no-telemetry-1.8.0.jar
noisium-1.0.2+mc1.20.x.jar
notenoughanimations-fabric-1.7.1-mc1.20.4.jar
Notes-1.20.4-2.1.0-fabric.jar
nyctophobia-dread-4.jar
owo-lib-0.12.5+1.20.3.jar
PaperDoll-v20.4.1-1.20.4-Fabric.jar
PickUpNotifier-v20.4.2-1.20.4-Fabric.jar
Potion-Blender-1.20.4-FABRIC-2.0.0.jar
PresenceFootsteps-1.11.2.jar
Prism-1.20.4-fabric-1.0.6.jar
puffish_skills-0.11.5-1.20.4-fabric.jar
PuzzlesLib-v20.4.36-1.20.4-Fabric.jar
Quad-1.1.4+1.20.4-Fabric.jar
realisticsleep-1.10.2+mc1.20.3-1.20.4.jar
reeses_sodium_options-1.7.2+mc1.20.4-build.102.jar
replaymod-1.20.4-2.6.15.jar
ResourcePackOverrides-v20.4.2-1.20.4-Fabric.jar
scorpions-fabric-1.20.1-1.3.2.jar
screenshot-to-clipboard-1.0.9-fabric.jar
SereneSeasons-fabric-1.20.4-9.3.0.18.jar
shulkerboxtooltip-fabric-4.0.8+1.20.4.jar
shutupdeadentities-mc1.20.4+1.0.jar
SlotCycler-v20.4.1-1.20.4-Fabric.jar
smallernetherportals-1.20.4-3.6.jar
smart-villagers-follow-emeralds-1.0.0.jar
SnowUnderTrees-2.2.0+1.20.4.jar
sodium-extra-0.5.4+mc1.20.4-build.116.jar
sodium-fabric-0.5.8+mc1.20.4.jar
sound-physics-remastered-fabric-1.20.4-1.3.1.jar
spawnermod-1.20.4-1.2.5+Fabric.jar
SpikySpikes-v20.4.1-1.20.4-Fabric.jar
spyglass-improvements-1.5+mc1.20.2+fabric.jar
stamina-meter-3.jar
starlight-1.1.3+fabric.f5dcd1a.jar
supermartijn642corelib-1.1.17-fabric-mc1.20.3.jar
sushimod-v1.0.12-fabric-1.20.4.jar
text-utilities-fabric-1.6.1+1.20.1.jar
ThinAir-v20.4.2-1.20.4-Fabric.jar
threadtweak-fabric-1.20.4-0.1.2.jar
TinySkeletons-v20.4.1-1.20.4-Fabric.jar
tooltipfix-1.1.1-1.20.jar
ToughAsNails-fabric-1.20.4-9.2.0.169.jar
TradingPost-v20.4.2-1.20.4-Fabric.jar
trashcans-1.0.18-fabric-mc1.20.jar
travelersbackpack-fabric-1.20.4-9.4.1.jar
trinkets-3.8.1.jar
TrueDarknessFork-1.0.2-1.20.x.jar
visuality-0.7.4+1.20.4.jar
VisualWorkbench-v20.4.1-1.20.4-Fabric.jar
wakes-0.2.2.jar
wardenhorn-1.7-fabric-mc1.20.1.jar
WhatTheBucket-Fabric-1.20.4-14.0.2.jar
woof-4.0.2+1.20.4.jar
worldplaytime-1.2.1-1.20.4-FABRIC.jar
yet-another-config-lib-fabric-3.3.1+1.20.4.jar
zombiehorsespawn-1.20.4-4.8.jar**

**Comment by Allexio** [comment]
I think I have the same issue as OP.
The problem seems to be with using items as icons rather than textures
If you replace your icons with texture-type icons, then your problem should be resolved.

**Comment by pufmat** [comment]
Fixed in version 0.11.6 of the mod.
