### ISSUE TITLE
puffish_skills seems to be missing from puffish_skills-0.12.0-1.20.4-neoforge

### ISSUE THREAD

**Issue by randomleech** [pufmat/skillsmod#85]
Hi.

EDIT: adding **puffish-attributes mod** fixed the issue

I downloaded newest update (puffish_skills-0.12.0-1.20.4-neoforge), replaced it in mods folder, made new world, and got a message about incorrect configuration (i also tried deleting all configs - thinking it would be recreated at game launch, but it was not; got message about something being missing).

Opened config.json

> {
> 	"version": 2,
> 
> 	"show_warnings": true,
> 
> 	**"categories": [
> 		"combat",
> 		"mining"
> 	]**
> }

 
Added "categories" section, since it was missing - at last with comparison with last version - but that did not help, I also changed "version" to 1, but still nothing.

(logs: 

> [Server thread/ERROR] [puffish_skills/]: [puffish_skills] Configuration could not be loaded:
> Expected valid attribute at `attribute` at `data` at index 0 at `rewards` at `root_melee_damage+3%` at `categories\combat\definitions.json` 

- and its repeated for every "skill":
root_melee_damage+3%
root_resistance+1%
resistance+1%
healing+5%
jump+5%
root_ranged_damage+3%
ranged_damage+3%
melee_damage+3%
stamina+5%
fortune+0.1
mining_speed+3%)

Then went into creative mode and typed /attributes @s , but there is nothing with "puf" attributes (for me its just minecraft and neoforge).

Also writhing: /puffish_skills points add @s mining 1 gives response (same for combat; Combat and Mining does not work: 

> There is no category with ID: puffish_skills:mining

PS / offtipic: I could set it up on my own.. just not higher jumps.. because.. which attribute is for higher jump? 
There is only minecraft:horse.jump_strength, but character does not have that attribute (there are also entity_gravity and step_height - but those are not right).

**Comment by pufmat** [comment]
> I downloaded newest update (puffish_skills-0.12.0-1.20.4-neoforge), replaced it in mods folder, made new world, and got a message about incorrect configuration (i also tried deleting all configs - thinking it would be recreated at game launch, but it was not; got message about something being missing).

In the recent update the mod was split, the core part is [Pufferfish's Skills](https://www.curseforge.com/minecraft/mc-mods/puffish-skills). Attributes are a separate mod [Pufferfish's Attributes](https://www.curseforge.com/minecraft/mc-mods/puffish-attributes). The default skill trees were also removed, but can still be downloaded as a data pack [Default Skill Trees](https://www.curseforge.com/minecraft/data-packs/default-skill-trees).

> PS / offtipic: I could set it up on my own.. just not higher jumps.. because.. which attribute is for higher jump?
There is only minecraft:horse.jump_strength, but character does not have that attribute (there are also entity_gravity and step_height - but those are not right).

Pufferfish's Attributes mod adds `puffish_skills:player.jump` attribute.
