### ISSUE TITLE
Loading NBT data error

### ISSUE THREAD

**Issue by Tresillo2017** [pufmat/skillsmod#89]
Game crash when loading a world or a server. 

Crash log:
https://mclo.gs/2vghgzM
Error:
```
[19:25:29] [Netty Client IO #4/ERROR]: Encountered exception while handling in channel with name "puffish_skills:show_category"
```

**Comment by pufmat** [comment]
This is likely caused by a different version of the mod on the server and client.

**Comment by Tresillo2017** [comment]
> This is likely caused by a different version of the mod on the server and client.

Is the same server version. But I will double check

**Comment by Tresillo2017** [comment]
Fixed by updating the mods
