### ISSUE TITLE
[Bug] Invalid configuration error

### ISSUE THREAD

**Issue by Anonyku05** [pufmat/skillsmod#93]
I have the latest version of pufferpush skills and pufferpush attributes on Minecraft 1.20.4 Fabric, and out of nowhere, i now get the error and the pufferpush skill tab shows this:
![image](https://github.com/pufmat/skillsmod/assets/48128391/b02e4651-82b7-4319-be30-eb2480c6ac7d)

Here is the latest.log file:
[latest.log](https://github.com/user-attachments/files/16033440/latest.log)

**Comment by pufmat** [comment]
From the game logs it looks like the Pufferfish's Attributes mod is not loaded.

**Comment by Anonyku05** [comment]
I downloaded the latest version and is now working fine.
